name: interactive_image_picker
description: "Handy widget that allows to manipulate picked images and retrieve them as wished."
version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.14.0
  image_picker: ^1.0.7
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  mocktail: ^1.0.2


flutter:
